const {chromium,webkit}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const files={'/':'index.html','/index.html':'index.html','/core.js':'core.js','/game.js':'game.js'};
const server=http.createServer((req,res)=>{const file=files[req.url];if(!file){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':file.endsWith('.html')?'text/html; charset=utf-8':'text/javascript; charset=utf-8'});res.end(fs.readFileSync(path.join(__dirname,file)));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/`;fs.mkdirSync('TestResults/instant',{recursive:true});
for(const [name,type] of [['chromium',chromium],['webkit',webkit]]){const browser=await type.launch();try{const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:2,isMobile:true,hasTouch:true});let errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(url);await page.locator('#new').click();
const place=async(x,y=0)=>{await page.evaluate(([x,y])=>{Object.assign(MMApp.state(),{x,y,vy:0,climb:null,grounded:true});},[x,y]);await page.waitForTimeout(100);};
const use=async()=>{await page.locator('#use').dispatchEvent('pointerdown',{pointerId:31,pointerType:'touch'});};
const solve=async()=>{const q=await page.evaluate(()=>MMApp.state().question);for(const d of String(q.answer))await page.locator('#key'+(d==='0'?'10':Number(d)-1)).click();await page.locator('#key11').click();await page.waitForTimeout(850);assert.equal(await page.evaluate(()=>MMApp.modal),'');};
let start=await page.evaluate(()=>MMApp.state().x);await page.locator('[data-hold=right]').dispatchEvent('pointerdown',{pointerId:21,pointerType:'touch'});await page.waitForTimeout(450);await page.locator('[data-hold=right]').dispatchEvent('pointerup',{pointerId:21,pointerType:'touch'});let stop=await page.evaluate(()=>MMApp.state().x);assert.ok(stop>start+1);await page.waitForTimeout(180);assert.ok(Math.abs(await page.evaluate(()=>MMApp.state().x)-stop)<.2);
await place(30);await use();assert.equal(await page.evaluate(()=>MMApp.modal),'question');await page.locator('#key10').click();await page.locator('#key11').click();assert.equal(await page.evaluate(()=>MMApp.modal),'question');const q1=await page.evaluate(()=>MMApp.state().question);for(const d of String(q1.answer))await page.locator('#key'+(d==='0'?'10':Number(d)-1)).click();await page.locator('#key11').click();await page.waitForTimeout(850);assert.equal(await page.evaluate(()=>MMApp.modal),'craft-guide');assert.match(await page.locator('#sheet').innerText(),/곡괭이 팔/);assert.match(await page.locator('#sheet').innerText(),/철 조각 2/);await page.locator('#craftGuideClose').click();await place(18);await use();assert.match(await page.locator('#craft0').innerText(),/지금 만들/);await page.locator('#craft0').click();assert.ok(await page.evaluate(()=>MMApp.state().owned[0]));await page.locator('#close').click();await page.evaluate(()=>MMApp.save());await page.reload();await page.locator('#continue').click();assert.ok(await page.evaluate(()=>MMApp.state().owned[0]));
await place(34);await use();assert.ok(await page.evaluate(()=>MMApp.state().flags.includes('mined')));
await place(38);await use();await place(44);await use();await place(40);await use();await place(44);await use();assert.ok(await page.evaluate(()=>MMApp.state().flags.includes('bridge')));
await place(44,8);await use();await place(48,8);await use();assert.ok(await page.evaluate(()=>MMApp.state().flags.includes('laser')));
for(const f of [1,2]){if(f===2){await place(38,16);await use();await solve();}const xs=await page.evaluate(f=>{let r=MM.rng(MMApp.state().seed+f*777),nums=[2,4,6];for(let i=2;i>0;i--){let j=r(i+1);[nums[i],nums[j]]=[nums[j],nums[i]];}return [2,4,6].map(n=>(f===1?16:42)+nums.indexOf(n)*4);},f);for(let x of xs)await place(x,8*f);assert.ok(await page.evaluate(k=>MMApp.state().flags.includes(k),f===1?'sequence':'boss.sequence'));}
await place(54,16);await use();assert.match(await page.locator('#goal').innerText(),/골렘/);assert.match(await page.locator('#goal').innerText(),/조사/);assert.match(await page.locator('#toast').innerText(),/보호막 0개/);await place(57,16);await use();assert.equal(await page.evaluate(()=>MMApp.modal),'clear');assert.ok(await page.locator('#nextChapter').isVisible());await page.locator('#nextChapter').click();assert.equal(await page.evaluate(()=>MMApp.campaign().chapter),'chapter-02');await page.evaluate(()=>MMApp.save());await page.reload();await page.locator('#continue').click();assert.equal(await page.evaluate(()=>MMApp.campaign().chapter),'chapter-02');
for(const [width,height] of [[393,852],[844,390],[320,568],[667,375]]){await page.setViewportSize({width,height});await page.waitForTimeout(150);for(const sel of ['#jump','#use','[data-hold=left]','[data-hold=down]']){const b=await page.locator(sel).boundingBox();assert.ok(b&&b.x>=0&&b.y>=0&&b.x+b.width<=width+.5&&b.y+b.height<=height+.5,`${name} ${sel} ${width}x${height}`);}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`TestResults/instant/${name}-${width}x${height}.png`});}
assert.deepEqual(errors,[]);console.log(`PASS ${name}: touch movement, answer feedback/close, crafting, real localStorage reload, bridge/mirrors/plates/boss, four mobile viewports`);
}finally{await browser.close();}}
server.close();})().catch(e=>{console.error(e);server.close();process.exit(1);});
