const test=require('node:test'),a=require('node:assert/strict');
let D,C,P;
try{D=require('./chapter-data.js');C=require('./core.js');P=require('./puzzles.js');}catch{}
test('ten-chapter engine is available',()=>{a.ok(D&&C&&P,'Campaign model and real puzzles must exist');});
test('all 10 chapters have in-bounds objectives and a question-providing golem',()=>{
 a.ok(D,'Chapter definitions are required');a.equal(D.list().length,10);
 for(const d of D.list()){
  a.equal(d.boss.kind,'golem');a.ok(d.boss.questions.length>=3);
  for(const t of [...d.tasks,d.boss]){a.ok(t.x>0&&t.x<d.width);a.ok(t.floor>=0&&t.floor<d.floors);}
 }
});
test('every generator uses the generator render contract',()=>{
 a.ok(D);const g=D.list().flatMap(d=>d.tasks).filter(x=>x.type==='repair');a.ok(g.length>=4);a.ok(g.every(x=>x.kind==='generator'));
});
test('legacy v2 completed chapter five unlocks six and retains materials',()=>{
 a.ok(C);const raw={v:2,seed:23,chapter:'chapter-05',completedChapters:['chapter-01','chapter-02','chapter-03','chapter-04','chapter-05'],unlockedChapters:['chapter-01','chapter-02','chapter-03','chapter-04','chapter-05'],campaignXp:36,inventory:{items:[4,3,2,1,1],owned:[true,true,true,true,true],equipped:[true,true,true,true,true],ench:[-1,-1,-1,-1,-1],unlocked:[]},chapterState:{seed:23,x:58,y:16,flags:['clear'],checkpoint:[30,16],visited:[],question:null}};
 const s=C.restore(JSON.stringify(raw));a.ok(s);a.equal(s.v,3);a.ok(s.unlockedChapters.includes('chapter-06'));a.deepEqual(s.inventory.items,raw.inventory.items);a.equal(s.xp,36);
});
test('real pipe connectivity rejects wrong ports, accepts the visible connected path',()=>{
 a.ok(P);const p=P.create('pipe',4);a.equal(P.solved(p),false);const solution=P.solvePipe(p);a.ok(solution);for(let i=0;i<solution.length;i++)p.rotations[i]=solution[i];a.equal(P.solved(p),true);a.ok(P.pipeTrace(p).reached.length>1);
});
test('laser outcome comes from reflected beam rather than a magic target array',()=>{
 a.ok(P);for(let seed=0;seed<8;seed++){let p=P.create('laser',seed);const solution=P.solveLaser(p);a.ok(solution);p.rotations=solution;a.equal(P.solved(p),true);a.ok(P.laserTrace(p).path.length>3);}
});
test('recipes remain distinct and direct crafting without a grid is rejected',()=>{
 a.ok(C);const s=C.fresh(7);s.inventory.items=[30,30,30,30,3];a.equal(C.craft(s,0).ok,false);a.equal(new Set(C.recipes.map(r=>r.join(','))).size,5);
 for(let i=0;i<5;i++){const old=s.inventory.items.slice();a.equal(C.craft(s,i,C.recipes[i]).ok,true);a.deepEqual(s.inventory.items,old.map((n,j)=>n-C.costs[i][j]));a.equal(C.craft(s,i,C.recipes[i]).ok,false);}
});
function walkTo(s,x,floor){for(let n=0;n<4000;n++){const st=C.session(s);if(Math.abs(st.y-floor*8)<.07&&Math.abs(st.x-x)<.25){C.move(s,0,0,false,1/60);return;}const f=Math.max(0,Math.min(2,Math.floor((st.y+.1)/8)));if(st.climb){C.move(s,0,floor*8>st.y?1:-1,false,1/60);continue;}if(f!==floor){const l=C.ladders(s).find(l=>floor>f?l[1]===f*8:l[2]===f*8);a.ok(l);if(Math.abs(st.x-l[0])>.15)C.move(s,Math.sign(l[0]-st.x),0,false,1/60);else C.move(s,0,floor>f?1:-1,false,1/60);}else C.move(s,Math.sign(x-st.x),0,false,1/60);}a.fail(`Cannot walk: ${s.chapter} ${C.session(s).x},${C.session(s).y} -> ${x},${floor*8}`);}
function solveModel(s,id){const p=C.puzzle(s,id);if(['number','rule'].includes(p.type))return C.submit(s,id,String(p.answer));if(['memory','order','sequence','equipment'].includes(p.type)){for(const v of p.sequence.slice(p.input.length)){const res=C.submit(s,id,v);a.ok(res.ok,`${s.chapter} ${id} ${JSON.stringify(res)}`);}return;}if(p.type==='pipe')p.rotations=P.solvePipe(p);else if(p.type==='laser')p.rotations=P.solveLaser(p);else if(p.type==='sokoban'){const moves=P.solveSokoban(p);a.ok(moves);moves.forEach(d=>P.sokobanMove(p,d));}else if(p.type==='weight'){let found=false;for(let mask=0;mask<1<<p.numbers.length;mask++){p.placed=p.numbers.map((_,i)=>mask&(1<<i)?i:-1).filter(i=>i>=0);if(P.solved(p)){found=true;break;}}a.ok(found);}a.ok(C.completeProblem(s,id));}
function advanceTask(s){for(let j=0;j<45;j++)C.move(s,0,0,false,1/60);const o=C.objective(s);if(o.kind==='craft'){walkTo(s,18,0);a.ok(C.craft(s,o.tool,C.recipes[o.tool]).ok);return;}if(o.kind==='equip'){a.ok(C.equip(s,o.tool));return;}walkTo(s,o.x,o.floor);if(o.kind==='boss'){const r=C.interact(s,'golem');a.equal(r.code,'boss');solveModel(s,r.question.id);return;}const t=C.currentTask(s);if(t.tool!==undefined)C.equip(s,t.tool);let r=C.interact(s,t.id);a.ok(r.ok,JSON.stringify(r));if(r.code==='working'){while(!C.has(s,t.id)){for(let j=0;j<30;j++)C.move(s,0,0,false,1/60);r=C.interact(s,t.id);a.ok(r.ok);}}else if(r.code==='jump'){C.move(s,0,0,true,1/60);for(let j=0;j<90;j++)C.move(s,0,0,false,1/60);a.ok(C.has(s,t.id));}else if(r.code==='puzzle'||r.code==='sequence'||r.code==='weight')solveModel(s,t.id);}
test('chapters 1–10 complete through reachable world routes and validated solutions',()=>{const s=C.fresh(184);for(const d of D.list()){a.ok(C.startChapter(s,d.id));for(let n=0;!C.has(s,'clear')&&n<45;n++)advanceTask(s);a.ok(C.has(s,'clear'),d.id);a.ok(s.completedChapters.includes(d.id));const restored=C.restore(C.serialize(s));a.ok(restored,'save reload '+d.id);a.deepEqual(restored.inventory,s.inventory);a.equal(restored.xp,s.xp);}a.equal(s.completedChapters.length,10);});
test('chapter switching retains unfinished puzzles and world coordinates without losing XP',()=>{const s=C.fresh(8);for(let n=0;!C.has(s,'clear')&&n<25;n++)advanceTask(s);a.ok(C.startChapter(s,'chapter-02'));C.session(s).x=23;const first=C.session(s);a.ok(C.startChapter(s,'chapter-01'));a.ok(C.startChapter(s,'chapter-02'));a.equal(C.session(s),first);a.equal(C.session(s).x,23);const r=C.restore(C.serialize(s));a.equal(C.session(r).x,23);a.equal(r.states['chapter-01'].flags.includes('clear'),true);});
test('owned wrench is not offered for crafting again and inactive wrench asks for equip',()=>{const s=C.fresh(31);s.completedChapters=['chapter-01'];s.unlockedChapters.push('chapter-02');s.inventory.owned[0]=s.inventory.owned[1]=true;s.inventory.equipped[0]=true;C.startChapter(s,'chapter-02');walkTo(s,14,0);C.interact(s,'c2.intro');a.equal(C.objective(s).kind,'equip');a.equal(C.objective(s).tool,1);C.equip(s,1);a.equal(C.objective(s).id,'c2.genA');a.doesNotMatch(C.objective(s).text,/만들/);});
test('arithmetic stays correct, reproducible and below 100 across 10 chapters',()=>{for(let seed=0;seed<100;seed++)for(const mode of ['add','sub','mul','div','missing','pattern','twoStep','divideAdd']){const p=P.number(seed,mode);a.deepEqual(p,P.number(seed,mode));a.ok(p.answer>=0&&p.answer<100);a.ok(P.press(p,String(p.answer)).solved);}});
test('all seeded pipe and laser boards are solvable',()=>{for(let n=0;n<50;n++){const p=P.create('pipe',n);a.equal(P.solved(p),false);p.rotations=P.solvePipe(p);a.ok(p.rotations);a.ok(P.solved(p));const l=P.create('laser',n,{level:n%10});a.equal(P.solved(l),false);l.rotations=P.solveLaser(l);a.ok(l.rotations);a.ok(P.solved(l));}});
test('both Sokoban layouts have a legal solution and support undo/reset without a cost',()=>{for(let level=1;level<=10;level++){const p=P.create('sokoban',1,{level}),moves=P.solveSokoban(p);a.ok(moves&&moves.length>=2);P.sokobanMove(p,moves[0]);a.ok(P.undo(p));a.deepEqual(p.player,p.initial.player);moves.forEach(d=>P.sokobanMove(p,d));a.ok(P.solved(p));P.reset(p);a.equal(P.solved(p),false);}});
test('wrong boss answers do not remove XP or materials and duplicates do not earn rewards',()=>{const s=C.fresh(19);while(!C.fieldDone(s))advanceTask(s);walkTo(s,53,2);const q=C.bossInfo(s).next,p=C.puzzle(s,q.id),before=C.serialize(s),xp=s.xp,items=s.inventory.items.slice();C.submit(s,q.id,'999');a.equal(s.xp,xp);a.deepEqual(s.inventory.items,items);a.equal(C.bossInfo(s).done,0);C.submit(s,q.id,String(p.answer));const after=s.xp;C.submit(s,q.id,String(p.answer));a.equal(s.xp,after);a.equal(C.bossInfo(s).done,1);});
test('golem cannot issue or clear a question before field objectives are finished',()=>{const s=C.fresh(20);C.session(s).x=53;C.session(s).y=16;a.equal(C.interact(s,'golem').code,'order');a.equal(C.submit(s,'boss.math','2').ok,false);a.equal(C.finish(s),false);a.equal(s.completedChapters.length,0);});
test('recipe mismatch, sparse grid and insufficient materials are atomic',()=>{const s=C.fresh(4);s.inventory.items=[20,20,20,20,0];for(const g of [undefined,new Array(9),Array(9).fill(-1),Array(8).fill(0)]){const before=C.serialize(s);a.equal(C.craft(s,0,g).ok,false);a.equal(C.serialize(s),before);}s.inventory.items=[0,0,0,0,0];a.equal(C.craft(s,0,C.recipes[0]).code,'materials');});
test('unknown or malformed saves are rejected',()=>{for(const x of ['{broken','{"v":99}',null,JSON.stringify({...C.fresh(2),chapter:'chapter-99'})])a.equal(C.restore(x),null);const s=C.fresh(2);s.inventory.items[0]=-1;a.equal(C.restore(JSON.stringify(s)),null);});
test('tool use aligns the player beside the generator so its rotor stays visible',()=>{const s=C.fresh(3);s.completedChapters=['chapter-01'];s.unlockedChapters.push('chapter-02');C.startChapter(s,'chapter-02');walkTo(s,14,0);C.interact(s,'c2.intro');s.inventory.owned[0]=s.inventory.owned[1]=true;C.equip(s,1);walkTo(s,30,0);a.ok(C.interact(s,'c2.genA').ok);a.ok(Math.abs(C.session(s).x-30)>=1);a.equal(C.session(s).action.tool,1);});
test('completed legacy chapter remains complete instead of requiring new tasks again',()=>{const old={v:1,seed:12,x:57,y:16,flags:['clear'],checkpoint:[30,16],items:[3,2,1,1,1],owned:[true,false,false,false,false],equipped:[true,false,false,false,false],ench:[-1,-1,-1,-1,-1],unlocked:[],xp:90,visited:[]};const s=C.restore(JSON.stringify(old));a.ok(s);a.equal(C.objective(s).kind,'clear');a.ok(s.unlockedChapters.includes('chapter-02'));});
test('wrong weight can be picked back up and put down without softlocking the player',()=>{const s=C.fresh(10);s.inventory.owned[0]=s.inventory.equipped[0]=true;C.session(s).flags.push('math','mined');const st=C.session(s);st.x=42.5;let r=C.interact(s,'bridge.weight.2');a.ok(r.ok);st.x=44;r=C.interact(s,'bridge');a.equal(r.code,'placed');a.equal(C.has(s,'bridge'),false);r=C.interact(s,'bridge');a.equal(r.code,'carried');st.x=42.5;r=C.interact(s,'drop');a.equal(r.code,'putdown');a.equal(st.carried,null);a.deepEqual(C.puzzle(s,'bridge').placed,[]);});
test('closing and restoring an unfinished numeric question keeps the same prompt',()=>{const s=C.fresh(11),p=C.puzzle(s,'math'),q=C.restore(C.serialize(s));a.equal(C.puzzle(q,'math').prompt,p.prompt);a.equal(C.puzzle(q,'math').answer,p.answer);});
test('reload preserves unfinished Sokoban boxes, player and a safe undo entry',()=>{const s=C.fresh(10);s.completedChapters=['chapter-01','chapter-02'];s.unlockedChapters=['chapter-01','chapter-02','chapter-03'];C.startChapter(s,'chapter-03');const p=C.puzzle(s,'c3.sokoban');const route=P.solveSokoban(p);a.ok(route.length>1);P.sokobanMove(p,route[0]);const after=C.restore(C.serialize(s));a.ok(after);const q=C.puzzle(after,'c3.sokoban');a.deepEqual(q.player,p.player);a.deepEqual(q.boxes,p.boxes);a.equal(q.history.length,1);a.ok(P.undo(q));a.deepEqual(q.player,p.initial.player);});
