const test=require('node:test'),a=require('node:assert/strict');
let D;try{D=require('./chapter-data.js');}catch{}
let R;try{R=require('./chapter-runtime.js');}catch{}
let C;try {C=require('./core.js');}catch{};
test('browser game core is available',()=>a.ok(C));
test('seed creates reproducible solvable arithmetic',()=>{for(let n=1;n<500;n++){let q=C.question(n,'math',n%5);a.deepEqual(q,C.question(n,'math',n%5));a.ok(Number.isInteger(q.answer)&&q.answer>=0&&q.answer<=100);a.equal(C.check(q,String(q.answer)),true);a.equal(C.check(q,''),false);}});
test('starter question enables first 3x3 craft without grinding',()=>{let s=C.fresh(1);a.equal(C.craft(s,0),false);a.equal(C.complete(s,'math'),true);a.equal(C.craft(s,0),false);a.equal(C.craft(s,0,C.recipes[0]),true);a.ok(s.owned[0]);});
test('reward is idempotent and invalid 3x3 craft never consumes',()=>{let s=C.fresh(2);C.complete(s,'math');let m=[...s.items],xp=s.xp;a.equal(C.complete(s,'math'),false);a.deepEqual(s.items,m);a.equal(s.xp,xp);a.equal(C.craft(s,0,Array(9).fill(-1)),false);a.deepEqual(s.items,m);});
test('all five tools have unique 3x3 recipes and charge exact ingredients',()=>{a.equal(C.recipes.length,5);a.equal(new Set(C.recipes.map(r=>r.join(','))).size,5);for(const r of C.recipes){a.equal(r.length,9);a.ok(r.some(v=>v>=0));}let s=C.fresh(3);s.owned[0]=true;s.items=[10,10,10,10,0];let old=[...s.items];a.equal(C.craft(s,4,Array(9).fill(-1)),false);a.deepEqual(s.items,old);a.ok(C.craft(s,4,C.recipes[4]));a.deepEqual(s.items,[8,10,8,9,0]);});
test('enchant is free after unlock and only active while equipped',()=>{let s=C.fresh(4);s.owned[4]=s.equipped[4]=true;s.xp=20;a.ok(C.enchant(s,4,0));a.equal(s.xp,10);a.ok(C.enchant(s,4,0));a.equal(s.xp,10);s.equipped[4]=false;a.equal(C.hasEnchant(s,4,0),false);});
test('locked wall prevents walking through; opened wall allows',()=>{let s=C.fresh(1);s.x=34;for(let i=0;i<60;i++)C.move(s,1,0,false,1/60);a.ok(s.x<35.3);s.flags.push('mined');for(let i=0;i<60;i++)C.move(s,1,0,false,1/60);a.ok(s.x>39);});
test('ladder climb reaches the next floor and can descend',()=>{let s=C.fresh(1);s.x=54;for(let i=0;i<160;i++)C.move(s,0,1,false,1/60);a.equal(s.y,8);for(let i=0;i<160;i++)C.move(s,0,-1,false,1/60);a.equal(s.y,0);});
test('boss cannot clear early, phases complete exactly once',()=>{let s=C.fresh(1);a.equal(C.finish(s),false);for(let k of ['boss.math','boss.sequence','boss.laser']) C.complete(s,k);a.equal(C.shields(s),0);a.ok(C.finish(s));a.equal(C.finish(s),false);});
test('save restores progress, rejects corrupt and different versions',()=>{let s=C.fresh(333);C.complete(s,'math');s.question=C.question(333,'math',0);let t=C.restore(JSON.stringify(s));a.equal(t.seed,333);a.ok(t.flags.includes('math'));a.deepEqual(t.question,s.question);a.equal(C.restore('{bad'),null);a.equal(C.restore('{"v":99}'),null);});

test('first craft and final boss objectives tell a child the exact next action',()=>{let s=C.fresh(7);C.complete(s,'math');let g=C.goal(s);a.match(g[2],/곡괭이 팔/);a.match(g[2],/철 조각 2/);a.match(g[2],/철판 1/);s.owned[0]=s.equipped[0]=true;s.flags.push('mined','bridge','laser','sequence','boss.math','boss.sequence','boss.laser');g=C.goal(s);a.match(g[2],/골렘/);a.match(g[2],/조사/);});

test('five chapter definitions expose stable ids and starts',()=>{a.ok(D);a.deepEqual(D.list().map(x=>x.id),['chapter-01','chapter-02','chapter-03','chapter-04','chapter-05']);a.deepEqual(D.get('chapter-02').start,[8,0]);a.equal(D.get('chapter-02').boss.id,'furnace-golem');});
test('v1 save migrates to campaign v2 without progress loss',()=>{let legacy=C.fresh(123);C.complete(legacy,'math');legacy.x=22;let restored=C.restore(JSON.stringify(legacy));a.equal(restored.v,2);a.equal(restored.chapter,'chapter-01');a.equal(restored.chapterState.x,22);a.ok(restored.chapterState.flags.includes('math'));});
test('chapter clear unlock is idempotent',()=>{let s=C.freshCampaign(9);C.markChapterComplete(s,'chapter-01');C.markChapterComplete(s,'chapter-01');a.deepEqual(s.unlockedChapters,['chapter-01','chapter-02']);});

test('data driven chapter one keeps current required route',()=>{a.ok(R);let s=C.freshCampaign(11);let o=R.objectiveFor(s);a.match(o.text,/숫자 장치/);R.completeStep(s,'math');o=R.objectiveFor(s);a.match(o.text,/곡괭이 팔/);s.inventory.owned[0]=s.inventory.equipped[0]=true;R.completeStep(s,'mined');a.match(R.objectiveFor(s).text,/8kg/);for(const k of ['bridge','laser','sequence','boss.math','boss.sequence','boss.laser'])R.completeStep(s,k);a.match(R.objectiveFor(s).text,/골렘/);a.match(R.objectiveFor(s).text,/조사/);});

test('chapter two questions keep multiplication and division child friendly',()=>{for(let n=1;n<=120;n++){let q=C.chapterQuestion(n,'chapter-02','generator',n%4);a.ok(['mul','div','add'].includes(q.kind));if(q.kind==='mul')a.ok([2,3,5].includes(q.a));if(q.kind==='div'){a.ok([2,3,5].includes(q.b));a.equal(q.a%q.b,0);}a.ok(q.answer>=0&&q.answer<=99);}});
test('chapter two objective chain reaches furnace golem finish',()=>{let s=C.freshCampaign(2);C.markChapterComplete(s,'chapter-01');C.startChapter(s,'chapter-02');let keys=[];for(let guard=0;guard<20;guard++){let o=R.objectiveFor(s);keys.push(o.key);if(o.key==='finish')break;R.completeStep(s,o.key);}a.deepEqual(keys,['c2.intro','craft1','c2.genA','c2.genB','c2.bridge','boss.math','boss.power','boss.plates','finish']);});

test('chapter three memory paths are seeded and short',()=>{let a1=R.memorySequence(77,'c3.memory'),a2=R.memorySequence(77,'c3.memory');a.deepEqual(a1,a2);a.equal(a1.length,3);a.ok(a1.every(n=>n>=0&&n<4));});
test('chapter three objective chain emphasizes booster space and memory',()=>{let s=C.freshCampaign(3);for(const id of ['chapter-01','chapter-02'])C.markChapterComplete(s,id);C.startChapter(s,'chapter-03');let keys=[];for(let i=0;i<20;i++){let o=R.objectiveFor(s);keys.push(o.key);if(o.key==='finish')break;R.completeStep(s,o.key);}a.deepEqual(keys,['c3.intro','craft2','c3.sokoban','c3.memory','c3.lift','boss.sokoban','boss.memory','boss.missing','finish']);});

test('chapter four rule puzzles have one deterministic answer',()=>{for(let seed=1;seed<80;seed++){let p=R.rulePuzzle(seed,'c4.rule');a.equal(p.options.length,3);a.equal(p.options.filter(x=>x.correct).length,1);a.deepEqual(p,R.rulePuzzle(seed,'c4.rule'));}});
test('chapter four objective chain uses sensor shield laser and logic',()=>{let s=C.freshCampaign(4);for(const id of ['chapter-01','chapter-02','chapter-03'])C.markChapterComplete(s,id);C.startChapter(s,'chapter-04');let keys=[];for(let i=0;i<20;i++){let o=R.objectiveFor(s);keys.push(o.key);if(o.key==='finish')break;R.completeStep(s,o.key);}a.deepEqual(keys,['c4.intro','craft4','c4.rule','c4.shield','c4.laser','boss.rule','boss.laser','boss.switch','finish']);});

test('chapter five final boss has five protection phases and explicit finish',()=>{let d=D.get('chapter-05');a.equal(d.boss.phases.length,5);let s=C.freshCampaign(5);for(const id of ['chapter-01','chapter-02','chapter-03','chapter-04'])C.markChapterComplete(s,id);C.startChapter(s,'chapter-05');let keys=[];for(let i=0;i<20;i++){let o=R.objectiveFor(s);keys.push(o.key);if(o.key==='finish')break;R.completeStep(s,o.key);}a.deepEqual(keys,['c5.number','c5.equipment','c5.spatial','c5.memory','boss.number','boss.equipment','boss.spatial','boss.memory','boss.core','finish']);});
test('chapter five questions combine easy arithmetic without oversized answers',()=>{for(let n=1;n<100;n++){let q=C.chapterQuestion(n,'chapter-05','core',n%5);a.ok(['mul','div','add','missing'].includes(q.kind));a.ok(q.answer>=0&&q.answer<=99);}});

test('all chapter objectives have target coordinates and actionable text',()=>{for(const d of D.list()){let list=R.steps[d.id];a.ok(list&&list.length);for(const row of list){a.equal(row.length,4);a.ok(Number.isFinite(row[1])&&Number.isFinite(row[2]));a.ok(typeof row[3]==='string'&&row[3].length>=8);}}});
test('tutorial cues appear once after acknowledgement',()=>{let s=C.freshCampaign(8);for(const id of ['first-wrench','first-booster','first-sensor','first-shield','first-sokoban','first-memory','first-rule','final-boss']){a.ok(R.tutorialCueFor(s,id));R.ackTutorial(s,id);a.equal(R.tutorialCueFor(s,id),null);}});

test('recipe ingredient counts match declared tool costs',()=>{for(let i=0;i<5;i++){let counts=[0,0,0,0,0];for(const v of C.recipes[i])if(v>=0)counts[v]++;a.deepEqual(counts,C.costs[i]);}});
