/* Mobile UI for the ten-chapter campaign. Storage remains on this same Pages origin. */
(()=>{'use strict';
const C=window.MM,P=window.MMPuzzles,D=window.MMChapters,$=id=>document.getElementById(id);
const KEY='mazemath.instant.v1',BACKUP='mazemath.instant.before-v3',VERSION='10.1';
const renderer=new MMRenderer($('world')),veil=$('veil'),sheet=$('sheet');
const materialNames=['철 조각','철판','기어','에너지석','코어'],materialIcons=['▰','▥','⚙','◆','★'];
const effects=[['메아리 · 장치 표식','행운 · 보물 힌트'],['빠른 수리','회로 감지'],['착지 보호','높은 길 안내'],['퍼즐로 실드 충전','보호막 표시'],['기억 경로 표시','다음 목표 안내']];
let s=C.fresh(Date.now()>>>0),running=false,mode='title',modalSerial=0,timers=new Set(),keys=new Set(),held=new Map(),jumpQueued=false,near=null,keyboard=null,toastTimer=0,effectTimer=0,worldEffect=null,lastSaved=0,lastFrame=0,acc=0,storageOK=true,lastPlateTime=-1,actionLock=false;
const testMode=new URLSearchParams(location.search).get('test')==='1'||window.__MM_TEST__===true;
const esc=x=>String(x).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function icon(i){const shapes=[`<path d="M16 9v20" stroke="#a67b43" stroke-width="5"/><path d="M4 12V6h24v6" fill="none" stroke="#bfcfbd" stroke-width="5"/>`,`<path d="M16 12v17M8 2v11h16V2" fill="none" stroke="#bfcfcd" stroke-width="6"/>`,`<path d="M9 2h14v20H9z" fill="#789ba0"/><path d="M6 22h21v6H6z" fill="#e7c778"/><path d="M11 29v3m10-3v3" stroke="#e8954d" stroke-width="4"/>`,`<path d="M5 3h22v14L16 30 5 17z" fill="#9bccb9" stroke="#eae4b1" stroke-width="2"/><path d="M16 7v14" stroke="#e7bb61" stroke-width="5"/>`,`<path d="M7 8h18v23H7z" fill="#e2d49d"/><path d="M11 12h10v9H11z" fill="#578e89"/><path d="M16 0v8M10 2h12" stroke="#d8b15d" stroke-width="3"/>`];return`<svg viewBox="0 0 32 34" aria-hidden="true">${shapes[i]||''}</svg>`;}
function current(){return C.session(s);}
function clearInput(){held.clear();keys.clear();jumpQueued=false;}
function cancelTimers(){timers.forEach(clearTimeout);timers.clear();keyboard=null;actionLock=false;}
function later(fn,ms){const serial=modalSerial,chapter=s.chapter;const t=setTimeout(()=>{timers.delete(t);if(serial===modalSerial&&chapter===s.chapter)fn();},ms);timers.add(t);return t;}
function save(){if(!running)return;try{localStorage.setItem(KEY,C.serialize(s));storageOK=true;}catch{storageOK=false;}lastSaved=current().clock;}
function readSave(){try{const raw=localStorage.getItem(KEY);const state=C.restore(raw);if(state&&JSON.parse(raw).v<3&&!localStorage.getItem(BACKUP))localStorage.setItem(BACKUP,raw);return state;}catch{storageOK=false;return null;}}
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2400);}
function effect(id,text='장치가 작동했어요!'){
 const t=C.objects(s).find(t=>t.id===id)||(id.startsWith('boss.')?C.definition(s).boss:null),st=current();worldEffect={x:t?.x??st.x,y:(t?.floor??Math.floor(st.y/8))*8,until:performance.now()/1000+1.4};
 const el=$('worldfx');el.innerHTML='✓ '+esc(text)+'<small>'+esc(C.objective(s).text)+'</small>';el.hidden=false;clearTimeout(effectTimer);effectTimer=setTimeout(()=>el.hidden=true,1600);
}
function open(kind,title,body){clearInput();cancelTimers();modalSerial++;mode=kind;veil.classList.add('open');sheet.innerHTML=`<div class="dialog-head"><h2 id="dialogTitle">${esc(title)}</h2><button class="btn" id="close" aria-label="닫기">×</button></div><div class="dialog-body">${body}</div>`;$('close').onclick=close;sheet.scrollTop=0;}
function close(){cancelTimers();modalSerial++;if(!running){title();return;}mode='';veil.classList.remove('open');clearInput();save();refresh();}
function bind(id,fn){const el=$(id);if(el)el.onclick=fn;}
function install(state){s=state;near=null;current().action=null;renderer.cx=current().x;renderer.cy=current().y+2.8;worldEffect=null;$('worldfx').hidden=true;lastPlateTime=-1;refresh();}
function title(){const old=readSave();open('title','모모의 블록 탐험',`<div class="center"><span class="tag">블록 모험 ${VERSION} · 챕터 1–10</span><div class="hero"><div class="face"></div></div><h1>모모와 만드는<br>열 개의 세계</h1><p>블록 미로를 탐험하고, 직접 도구를 만들고,<br>골렘의 문제를 풀어 주세요.</p></div><div class="stack">${old?'<button class="btn primary wide" id="continue">이어하기</button><button class="btn wide" id="chaptersTitle">챕터 선택</button>':''}<button class="btn wide ${old?'':'primary'}" id="new">새 탐험 시작</button></div><p class="sub center">설치 없는 모바일 웹판 · Unity 본편과 별도 저장<br>같은 브라우저에서 기록이 이어집니다.</p>`);
 bind('continue',()=>{install(old);running=true;close();});bind('chaptersTitle',()=>{install(old);running=false;chapterSelect();});bind('new',()=>{if(old){open('confirm','새 탐험','<p>이어하기 기록은 백업하고 새 모험을 시작할까요?</p><button class="btn primary wide" id="newConfirm">새로 시작</button>');bind('newConfirm',()=>{try{localStorage.setItem(BACKUP,C.serialize(old));}catch{}newRun();});}else newRun();});
}
function newRun(){install(C.fresh((Date.now()^(Math.random()*0xffffffff))>>>0));running=true;close();save();notify('오른쪽 숫자 장치로 가서 조사해요.');}
function chapterSelect(){open('chapters','열 개의 세계',`<div class="chapter-grid">${D.list().map(d=>{const unlocked=s.unlockedChapters.includes(d.id),done=s.completedChapters.includes(d.id);return`<article class="chapter-card" id="${d.id}"><span class="tag">${d.order}장</span><h3>${esc(d.title)}</h3><p>${done?'완료 · 다시 둘러보기':unlocked?'도전 가능':`${d.order-1}장 완료 후 열려요`}</p><button class="btn ${unlocked&&!done?'primary':''}" id="go-${d.id}" ${unlocked?'':'disabled'}>${done?'둘러보기':unlocked?'탐험 시작':'잠김'}</button></article>`;}).join('')}</div>`);D.list().forEach(d=>bind('go-'+d.id,()=>switchChapter(d.id)));}
function switchChapter(id){if(running)save();if(!C.startChapter(s,id)){notify('이전 챕터를 먼저 완료해요.');return;}install(s);running=true;close();save();notify(D.get(id).title+' · 모모와 출발!');}
function pause(){if(!running){title();return;}save();open('pause','잠깐 쉬어 가요',`<p>진행 기록을 저장했어요.</p><div class="stack"><button class="btn primary" id="resume">계속 탐험</button><button class="btn" id="selectChapters">챕터 선택</button><button class="btn" id="bagOpen">탐험 가방</button><button class="btn" id="checkpoint">안전한 사다리로 돌아가기</button><button class="btn" id="help">조작 방법</button><button class="btn" id="home">처음 화면</button></div><p class="sub">${storageOK?'자동 저장 중':'저장이 제한된 브라우저예요. 창을 닫지 마세요.'}<br>Block Quest ${VERSION} · 10장 모바일 웹판</p>`);bind('resume',close);bind('selectChapters',chapterSelect);bind('bagOpen',bag);bind('checkpoint',()=>{const st=current();[st.x,st.y]=st.checkpoint;st.vy=0;st.climb=null;close();});bind('help',help);bind('home',()=>{save();running=false;title();});}
function help(){open('help','모모의 탐험 안내','<div class="help"><b>← →</b> 이동 · <b>↑ ↓</b> 사다리<br><b>점프</b>로 발판을 넘어요.<br><b>아래 도구 슬롯</b>을 선택하고 <b>캐기 / 수리 / 조사</b>를 눌러요.</div><p>모든 도구는 작업대에서 <b>3×3 조합</b>으로 만들어요. 조합법 보기를 눌러도 벌점은 없어요.</p><p>상자는 가까이서 들어 저울에 놓아요.<br>숫자 발판은 직접 밟아요. 눌린 발판과 다음 숫자를 확인하세요.</p><p>골렘에게 말을 걸면 문제를 줘요. 마지막 문제를 맞히면 다음 챕터가 열려요.</p>');}
function resources(){return`<div class="resources">${materialNames.map((n,i)=>`${materialIcons[i]} ${n} <b>${s.inventory.items[i]}</b>`).join(' · ')}<br>지식 경험치 <b>${s.xp} XP</b></div>`;}
function bag(){open('bag','탐험 가방',resources()+`<div class="inventory-list">${D.tools.map((t,i)=>`<div class="inventory-row">${icon(i)}<div class="body"><b>${esc(t)}</b><small>${s.inventory.owned[i]?(s.inventory.equipped[i]?'장착 중':'가방에 있어요'):'작업대에서 제작해요'}</small></div><button class="btn" id="equip${i}" ${C.owned(s,i)?'':'disabled'}>선택</button></div>`).join('')}</div>`);D.tools.forEach((_,i)=>bind('equip'+i,()=>{C.equip(s,i);save();bag();refresh();}));}
function atBench(){return Math.abs(current().x-18)<2&&Math.abs(current().y)<1;}
function recommendedTool(){const missing=C.definition(s).requiredTools.find(i=>!C.owned(s,i));return missing??current().selectedHotbar??0;}
function workshop(selected=recommendedTool()){
 if(!atBench()){notify('제작은 1층 작업대 앞에서 해요.');return;}
 let grid=Array(9).fill(-1),pick=0,showHint=selected===0&&!C.owned(s,0);const isOwned=C.owned(s,selected);
 open('workshop','3×3 제작대',`<div class="tabs"><button class="btn primary" id="craftTab">조합 제작</button><button class="btn" id="enchantTab">인챈트</button></div>${resources()}<div class="recipe-list">${D.tools.map((n,i)=>`<button class="btn ${i===selected?'primary':''}" id="recipe${i}" aria-pressed="${i===selected}">${icon(i)} ${esc(n)}${C.owned(s,i)?' ✓':''}</button>`).join('')}</div><div class="help center"><b id="craftTarget">${esc(D.tools[selected])}</b><br>${isOwned?'이미 가지고 있어요. 다시 만들 필요가 없어요.':C.costs[selected].map((v,i)=>v?`${materialNames[i]} ${v}`:'').filter(Boolean).join(' + ')}</div><div class="pickers">${[0,1,2,3].map(i=>`<button class="btn" id="pick${i}">${materialIcons[i]} ${materialNames[i]} (${s.inventory.items[i]})</button>`).join('')}</div><div class="craft-layout"><div class="recipe" id="craftGrid">${grid.map((_,i)=>`<button class="btn" id="cell${i}" aria-label="제작 칸 ${i+1}">·</button>`).join('')}</div><span class="craft-arrow">→</span><div class="result-slot"><div id="resultIcon">?</div><small id="craftResult">결과</small></div></div><div class="tabs"><button class="btn" id="recipeHint">조합법 보기</button><button class="btn" id="clearGrid">칸 비우기</button></div><button class="btn primary wide" id="makeCraft" disabled>${isOwned?'이미 보유 중':esc(D.tools[selected])+' 제작하기'}</button><div class="feedback" id="craftFeedback">${showHint?'반투명 모양을 따라 재료를 놓아보세요.':'재료를 고른 뒤 놓을 칸을 눌러요.'}</div><p class="sub">틀린 조합은 재료가 줄지 않아요. 같은 재료가 놓인 칸을 다시 누르면 비워져요.</p>`);
 function render(){for(let i=0;i<9;i++){const v=grid[i],hint=C.recipes[selected][i];$('cell'+i).innerHTML=v>=0?materialIcons[v]:showHint&&hint>=0?`<span class="ghost">${materialIcons[hint]}</span>`:'·';$('cell'+i).setAttribute('aria-label',`제작 칸 ${i+1}: ${v<0?'빈칸':materialNames[v]}`);}const matched=grid.every((v,i)=>v===C.recipes[selected][i]);$('makeCraft').disabled=!matched||isOwned;$('resultIcon').innerHTML=matched?icon(selected):'?';$('craftResult').textContent=matched?D.tools[selected]:'결과';$('recipeHint').textContent=showHint?'조합법 숨기기':'조합법 보기';[0,1,2,3].forEach(i=>$('pick'+i).classList.toggle('chosen',i===pick));}
 D.tools.forEach((_,i)=>bind('recipe'+i,()=>workshop(i)));[0,1,2,3].forEach(i=>bind('pick'+i,()=>{pick=i;render();}));grid.forEach((_,i)=>bind('cell'+i,()=>{grid[i]=grid[i]===pick?-1:pick;render();}));bind('recipeHint',()=>{showHint=!showHint;render();});bind('clearGrid',()=>{grid.fill(-1);render();});bind('enchantTab',enchantMenu);bind('craftTab',()=>workshop(selected));
 bind('makeCraft',()=>{const result=C.craft(s,selected,grid);if(result.ok){save();close();effect('workshop',D.tools[selected]+' 제작 · 장착 완료!');refresh();}else{$('craftFeedback').textContent=result.code==='first-tool'?'먼저 곡괭이 팔을 만들어 주세요.':result.code==='materials'?'재료가 모자라요. 준비 상자나 퍼즐을 확인해요.':result.code==='owned'?'이미 가지고 있는 도구예요.':'조합법을 한 번 더 확인해요.';}});render();
}
function enchantMenu(){if(!atBench()){notify('작업대에서 인챈트해요.');return;}open('enchant','도구 인챈트',resources()+`<p class="sub">처음 해금할 때 10 XP · 해금한 효과로 다시 바꾸는 것은 무료예요.</p><div class="inventory-list">${D.tools.map((name,i)=>`<div class="help"><b>${esc(name)}</b><div class="tabs">${[0,1].map(v=>`<button class="btn ${s.inventory.ench[i]===v?'primary':''}" id="enchant${i}-${v}" ${C.owned(s,i)?'':'disabled'}>${esc(effects[i][v])}${s.inventory.unlocked.includes(i*2+v)?' ✓':' · 10 XP'}</button>`).join('')}</div></div>`).join('')}</div><button class="btn wide" id="backCraft">3×3 제작대로</button>`);D.tools.forEach((_,i)=>[0,1].forEach(v=>bind(`enchant${i}-${v}`,()=>{if(C.enchant(s,i,v)){save();enchantMenu();notify('인챈트를 장착했어요.');}else notify('해금하려면 10 XP가 필요해요.');})));bind('backCraft',()=>workshop());}
function mapUI(){const st=current(),room=Math.floor((st.y+.2)/8)*5+Math.floor(st.x/12);open('map',C.definition(s).title+' 지도',`<p>내가 지나간 방은 밝게 보여요.</p><div class="map-grid">${Array.from({length:15},(_,j)=>{const i=(2-Math.floor(j/5))*5+j%5;return`<div class="map-room ${st.visited.includes(i)?'visited':''} ${i===room?'here':''}">${i===room?'나':st.visited.includes(i)?'발견':'?'}</div>`;}).join('')}</div><div class="help">${esc(C.objective(s).text)}</div>`);}
function chooseTool(i){if(!C.equip(s,i)){notify(D.tools[i]+'은 작업대에서 먼저 만들어요.');return;}save();refresh();}
function showBoss(){const result=C.interact(s,'golem'),d=C.definition(s),b=C.bossInfo(s);if(result.code==='clear'){chapterClear();return;}if(!result.ok){open('boss',d.boss.label,`<div class="hero golem"><div class="face"></div></div><div class="boss-line">먼저 이 장치를 도와줄래?<br>${esc(C.objective(s).text)}</div><div class="stack"><button class="btn primary" id="bossBack">장치로 돌아가기</button></div>`);bind('bossBack',close);return;}
 const q=result.question;open('boss',d.boss.label,`<div class="hero golem"><div class="face"></div></div><div class="boss-progress">${Array.from({length:b.total},(_,i)=>`<span class="rune ${i<b.done?'done':''}">${i<b.done?'✓':i+1}</span>`).join('')}</div><div class="boss-line">“${esc(q.prompt)}”</div><p class="center">${b.done+1} / ${b.total}번째 문제</p><button class="btn primary wide" id="acceptQuestion">골렘의 문제 받기</button><p class="sub center">틀려도 괜찮아요. 힌트나 다시 보기를 써도 돼요.</p>`);bind('acceptQuestion',()=>openPuzzle(q.id,true));
}
function completeUI(id){save();const el=$('feedback');if(el){el.textContent='정답이에요! 잘했어요.';el.classList.remove('bad');}sheet.querySelectorAll('.dialog-body button').forEach(b=>b.disabled=true);later(()=>{close();effect(id,id.startsWith('boss.')?'골렘: 정답이야! 잘했어.':'장치가 작동했어요!');if(C.has(s,'clear'))later(chapterClear,800);},650);}
function chapterClear(){const d=C.definition(s),next=D.list().find(x=>x.order===d.order+1);open('clear',s.completedChapters.length===10?'열 개의 세계 탐험 성공!':d.title+' 완료',`<div class="hero golem"><div class="face"></div></div><h1 class="center">잘했어요, 탐험가!</h1><p class="center">${s.completedChapters.length===10?'모모와 모든 세계의 코어를 되찾았어요.':'골렘의 문제를 모두 해결했어요.'}</p><div class="help center">완료한 챕터 ${s.completedChapters.length} / 10<br>지식 경험치 ${s.xp} XP</div><div class="stack">${next?`<button class="btn primary" id="nextChapter">${next.order}장 · ${esc(next.title)}으로</button>`:''}<button class="btn" id="chapters">챕터 선택</button><button class="btn" id="keep">남은 보물 찾아보기</button></div>`);if(next)bind('nextChapter',()=>switchChapter(next.id));bind('chapters',chapterSelect);bind('keep',close);}
function openPuzzle(id,boss=false){
 const desc=C.descriptor(s,id),p=C.puzzle(s,id);if(!p||C.has(s,id))return;const titleText=boss?C.definition(s).boss.label+'의 문제':desc.label;
 if(p.type==='number')numberUI(id,titleText,boss);
 else if(p.type==='rule')ruleUI(id,titleText,boss);
 else if(['memory','order','equipment'].includes(p.type))sequenceUI(id,titleText,boss);
 else if(p.type==='pipe')pipeUI(id,titleText,boss);
 else if(p.type==='laser')laserUI(id,titleText,boss);
 else if(p.type==='sokoban')sokobanUI(id,titleText,boss);
}
function numberUI(id,titleText,boss){const p=C.puzzle(s,id);let answer='',locked=false;open(boss?'boss-question':'question',titleText,`<div class="quizrow"><div>${boss?'<span class="tag" id="questionSpeaker">골렘이 낸 문제</span>':''}<div class="equation" id="questionPrompt">${esc(p.prompt)}</div><div class="answer" id="answer" aria-live="polite">?</div><div class="feedback" id="feedback">숫자를 입력해 주세요.</div><button class="btn small" id="hint">모모의 힌트</button></div><div class="keys">${['1','2','3','4','5','6','7','8','9','⌫','0','확인'].map((v,i)=>`<button class="btn ${i===11?'primary':''}" id="key${i}">${v}</button>`).join('')}</div></div>`);save();
 const render=()=>{$('answer').textContent=answer||'?';};function submit(){if(locked||!answer)return;const r=C.submit(s,id,answer);if(r.solved){locked=true;completeUI(id);}else{$('feedback').textContent='괜찮아요. 한 번 더 생각해요.';$('feedback').classList.add('bad');answer='';render();save();}}
 for(let i=0;i<12;i++)bind('key'+i,()=>{if(locked)return;if(i<9&&answer.length<3)answer+=i+1;else if(i===9)answer=answer.slice(0,-1);else if(i===10&&answer.length<3)answer+='0';else if(i===11)submit();render();});let hints=0;bind('hint',()=>{$('feedback').textContent=++hints>1?'함께 확인해요: '+p.answer:p.hint;});keyboard=e=>{if(locked)return;if(/^\d$/.test(e.key)&&answer.length<3){answer+=e.key;render();}else if(e.key==='Backspace'){answer=answer.slice(0,-1);render();}else if(e.key==='Enter')submit();};
}
function ruleUI(id,titleText,boss){const p=C.puzzle(s,id);open(boss?'boss-question':'rule',titleText,`<p class="help" id="questionPrompt">${esc(p.prompt)}</p><div class="stack">${p.options.map((n,i)=>`<button class="btn wide" id="rule${i}">${n}</button>`).join('')}</div><div class="feedback" id="feedback">두 조건을 하나씩 확인해요.</div><button class="btn" id="hint">모모의 힌트</button>`);save();p.options.forEach((n,i)=>bind('rule'+i,()=>{const r=C.submit(s,id,n);if(r.solved)completeUI(id);else{$('feedback').textContent='조건과 다른 답이에요. 다시 골라요.';$('feedback').classList.add('bad');save();}}));bind('hint',()=>{$('feedback').textContent=p.hint;});}
function sequenceUI(id,titleText,boss){const p=C.puzzle(s,id),memory=p.type==='memory',equipment=p.type==='equipment';let previewSerial=0,locked=memory;const symbols=['▲','■','●','◆'];const choices=equipment?[0,1,2,3,4]:memory?[0,1,2,3]:p.sequence.slice();
 const clues=['균열벽을 열려면 어떤 도구가 필요할까?','고장 난 발전기를 고치려면?','높은 리프트에 오르려면?','전기장을 안전하게 지나려면?','숨은 규칙 단서를 찾으려면?'];
 open(boss?'boss-question':memory?'memory':'order',titleText,`<p>${equipment?'상황에 맞는 도구를 선택해요.':memory?'빛나는 순서를 보고, 같은 순서로 눌러요.':'표시된 순서대로 눌러 주세요.'}</p><div class="help center" id="sequencePrompt"></div><div class="equation" id="memoryShow"></div><div class="${equipment?'stack':'memory-keys'}">${choices.map((v,i)=>`<button class="btn" id="seq${i}" data-value="${v}">${equipment?esc(D.tools[v]):memory?symbols[v]:v}</button>`).join('')}</div><div class="feedback" id="feedback"></div>${memory?'<button class="btn wide" id="replay">순서 다시 보기</button>':''}`);save();
 function render(){const n=p.input.length;$('sequencePrompt').textContent=equipment?clues[p.sequence[n]]||'도구 선택 성공!':memory?`${p.sequence.length}개를 기억해요. 다시 보아도 괜찮아요.`:p.sequence.join(' → ');if(!memory)$('memoryShow').textContent=equipment?`${n} / 5`:p.sequence.map((v,i)=>i<n?v+' ✓':v).join('  ');$('feedback').textContent=`${n} / ${p.sequence.length}`;choices.forEach((_,i)=>$('seq'+i).disabled=locked);}
 function preview(){const serial=++previewSerial;locked=true;p.input=[];render();$('memoryShow').textContent=p.sequence.map(i=>symbols[i]).join('  ');$('feedback').textContent='지금 순서를 보세요.';later(()=>{if(serial!==previewSerial)return;locked=false;$('memoryShow').textContent='?  '.repeat(p.sequence.length);render();$('feedback').textContent='같은 순서로 눌러요.';},900+p.sequence.length*150);}
 choices.forEach((value,i)=>bind('seq'+i,()=>{if(locked)return;const r=C.submit(s,id,value);if(r.solved){locked=true;completeUI(id);}else if(!r.ok){if(equipment&&r.code==='craft'){$('feedback').textContent='이 도구를 작업대에서 먼저 만들어 주세요.';return;}render();$('feedback').textContent='괜찮아요. 처음부터 다시 해요.';if(memory)later(preview,400);}else render();save();}));if(memory){bind('replay',preview);preview();}else{locked=false;render();}
}
function pipeSvg(mask,flow){let paths='';const ends=[[30,0],[60,30],[30,60],[0,30]];for(let d=0;d<4;d++)if(mask&(1<<d))paths+=`M30 30 L${ends[d][0]} ${ends[d][1]} `;return`<svg viewBox="0 0 60 60"><path d="${paths}" fill="none" stroke="#536958" stroke-width="15"/><path d="${paths}" fill="none" stroke="${flow?'#f5c86e':'#d5d7b7'}" stroke-width="8"/><circle cx="30" cy="30" r="7" fill="${flow?'#ffebb0':'#bbc6a0'}"/></svg>`;}
function pipeUI(id,titleText,boss){const p=C.puzzle(s,id);let locked=false;open(boss?'boss-question':'pipe',titleText,`<p class="help">왼쪽 입구에서 오른쪽 용광로까지 <b>끊김 없이 연결</b>해요. 칸을 누르면 90° 돌아가요.<br>실제로 흐르는 관만 노랗게 켜져요.</p><div class="pipe-layout"><div class="pipe-end">🔥<br>입구 →</div><div class="pipe-grid">${p.cells.map((cell,i)=>`<button class="pipe-cell" id="pipe${i}" aria-label="배관 ${Math.floor(i/3)+1}행 ${i%3+1}열" ${cell?'':'disabled'}></button>`).join('')}</div><div class="pipe-end">→ 🏭<br>도착</div></div><div class="feedback" id="pipeProgress"></div><div class="feedback" id="feedback"></div><button class="btn small" id="hint">연결 힌트</button>`);
 function render(){const tr=P.pipeTrace(p);p.cells.forEach((cell,i)=>{const e=$('pipe'+i);e.innerHTML=cell?pipeSvg(P.ports(cell,p.rotations[i]),tr.reached.includes(i)):'';e.classList.toggle('flowing',tr.reached.includes(i));});$('pipeProgress').textContent=tr.solved?'용광로에 도착했어요!':`불꽃이 흐르는 관 ${tr.reached.length} / ${p.cells.filter(Boolean).length}`;}
 p.cells.forEach((cell,i)=>{if(cell)bind('pipe'+i,()=>{if(locked)return;P.rotate(p,i);render();save();if(P.solved(p)&&C.completeProblem(s,id)){locked=true;completeUI(id);}});});bind('hint',()=>{$('feedback').textContent='입구에 닿는 관부터 살펴봐요. 두 관의 열린 끝이 서로 마주 봐야 해요.';});render();save();
}
function laserUI(id,titleText,boss){const p=C.puzzle(s,id);let locked=false;open(boss?'boss-question':'laser',titleText,'<p class="help">빛이 수정 <b>◆</b>에 닿도록 거울을 돌려요. 지금 보이는 빛의 경로가 실제 판정이에요.</p><div id="laserBoard" class="laser-board"></div><div class="feedback" id="feedback"></div><button class="btn small" id="hint">반사 힌트</button>');
 function render(){const tr=P.laserTrace(p),pos=([x,y])=>[(x+1)*50+25,y*50+25],points=tr.path.map(v=>pos(v).join(',')).join(' '),[tx,ty]=pos(p.target);let lines='';for(let i=0;i<6;i++)lines+=`<path d="M50 ${i*50}H300 M${50+i*50} 0V250" stroke="#aac3b5" stroke-width="1"/>`;
 $('laserBoard').innerHTML=`<svg viewBox="0 0 350 250" aria-label="레이저 경로">${lines}<text x="8" y="${pos(p.source)[1]+6}" font-size="24" fill="#b47738">→</text><polyline points="${points}" fill="none" stroke="#b48a3d" stroke-width="8"/><polyline points="${points}" fill="none" stroke="#ffe29a" stroke-width="4"/><text x="${tx}" y="${ty+10}" text-anchor="middle" font-size="31" fill="${tr.solved?'#67a780':'#548789'}">◆</text></svg>${p.mirrors.map((m,i)=>{const [x,y]=pos(m);return`<button class="mirror-button" id="mirror${i}" style="left:${x/350*100}%;top:${y/250*100}%" aria-label="거울 ${i+1} 회전">${p.rotations[i]===0?'╱':'╲'}</button>`;}).join('')}`;
 p.mirrors.forEach((_,i)=>bind('mirror'+i,()=>{if(locked)return;P.rotate(p,i);render();save();if(P.solved(p)&&C.completeProblem(s,id)){locked=true;completeUI(id);}}));}
 bind('hint',()=>{$('feedback').textContent='빛이 거울에 닿으면 방향이 꺾여요. 먼저 빛이 닿은 거울부터 돌려 보세요.';});render();save();
}
function sokobanUI(id,titleText,boss){const p=C.puzzle(s,id);let locked=false;open(boss?'boss-question':'sokoban',titleText,'<p>● 탐험가로 ▣ 상자를 밀어 <b>★ 목표 칸</b>에 놓아요. 당기기는 안 돼요.</p><div class="soko-grid" id="sokoGrid"></div><div class="soko-pad"><button class="btn" id="sLeft">←</button><button class="btn" id="sUp">↑</button><button class="btn" id="sDown">↓</button><button class="btn" id="sRight">→</button></div><div class="problem-tools"><button class="btn" id="sUndo">한 칸 되돌리기</button><button class="btn" id="sReset">퍼즐 다시 시작</button></div><div class="feedback" id="feedback"></div>');
 function render(){const g=$('sokoGrid');g.style.gridTemplateColumns=`repeat(${p.width},1fr)`;let html='';for(let y=0;y<p.height;y++)for(let x=0;x<p.width;x++){const is=(v)=>v[0]===x&&v[1]===y,wall=p.walls.some(is),goal=p.goals.some(is),box=p.boxes.some(is),player=is(p.player);html+=`<div class="soko-cell ${wall?'wall':''} ${goal?'goal':''}" aria-label="${box?'상자':player?'탐험가':goal?'목표':'바닥'}">${wall?'':box?(goal?'▣✓':'▣'):player?'●':goal?'★':''}</div>`;}g.innerHTML=html;$('sUndo').disabled=!p.history.length;}
 const move=d=>{if(locked)return;P.sokobanMove(p,d);render();save();if(P.solved(p)&&C.completeProblem(s,id)){locked=true;completeUI(id);}};bind('sUp',()=>move(0));bind('sRight',()=>move(1));bind('sDown',()=>move(2));bind('sLeft',()=>move(3));bind('sUndo',()=>{if(locked)return;P.undo(p);render();save();});bind('sReset',()=>{if(locked)return;P.reset(p);render();save();});render();save();
}
function act(){if(!running||mode||actionLock)return;if(current().carried&&near?.kind!=='scale'){C.interact(s,'drop');save();refresh();notify('상자를 내려놓았어요.');return;}if(!near)return;const t=near;
 if(t.id==='golem'){showBoss();return;}
 const r=C.interact(s,t.id);if(!r.ok){const msg={busy:'도구가 움직이는 중이에요.',far:'조금 더 가까이 가요.',complete:'이미 해결한 장치예요.',owned:'이미 가지고 있어요.',carrying:'먼저 들고 있는 상자를 저울에 놓아요.'};if(['select','equip'].includes(r.code))notify(`아래에서 ${D.tools[r.tool]}을 선택해 주세요.`);else if(r.code==='craft')notify(`작업대에서 ${D.tools[r.tool]}을 3×3으로 만들어요.`);else notify(r.text||msg[r.code]||'현재 목표부터 해결해요.');return;}
 if(r.code==='workshop')workshop();
 else if(r.code==='puzzle'){if(r.delay){clearInput();actionLock=true;later(()=>{actionLock=false;openPuzzle(r.id);},r.delay);}else openPuzzle(r.id);}
 else if(r.code==='sequence')notify('발판을 직접 밟아요. 눌린 숫자는 초록색 ✓, 다음 숫자는 노란색이에요.');
 else if(r.code==='weight')notify('옆의 상자를 조사해 들고, 저울에서 다시 조사해 내려놓아요.');
 else if(r.code==='carried')notify('상자를 들었어요. 저울 앞으로 가서 놓아요.');
 else if(r.code==='placed'){const p=C.puzzle(s,t.id);notify(`현재 ${p.placed.reduce((n,i)=>n+p.numbers[i],0)}kg / 목표 ${p.target}kg`);}
 else if(r.code==='jump'){jumpQueued=true;notify('부스터 점프!');}
 else if(r.code==='working')notify(`${t.label} · ${r.hits}/${r.total}`);
 else if(r.code==='supply'){const g=C.objective(s);notify(g.kind==='craft'?`재료가 준비됐어요. ${D.tools[g.tool]}을 만들어요.`:'이미 만든 도구를 그대로 사용해요.');effect(t.id,'탐험 준비 완료');}
 else if(['done','cache'].includes(r.code))effect(t.id,r.code==='done'?'장치가 작동했어요!':'보물을 찾았어요!');
 save();refresh();
}
function refresh(){const st=current(),d=C.definition(s),o=C.objective(s);$('goal').textContent=running?o.text:'모모와 열 개의 세계로 떠나요.';$('status').textContent=`${d.order}장 · ${Math.max(1,Math.min(3,Math.floor((st.y+.2)/8)+1))}층 · ${s.xp} XP`;
 const t=C.currentTask(s);if(t?.type==='sequence'){const p=C.puzzle(s,t.id);$('sequenceInfo').textContent=p.sequence.map((v,i)=>i<p.input.length?v+' ✓':v).join(' → ');}else if(st.plateEvent&&st.clock<st.plateEvent.until){$('sequenceInfo').textContent=st.plateEvent.ok?'발판 성공! 다음 목표로 가요.':'다시 첫 숫자부터 시작해요.';}else $('sequenceInfo').textContent='';
 const old=near;near=C.objects(s).filter(t=>Math.abs(st.x-t.x)<=2&&(Math.abs(st.y-t.floor*8)<2.1)).sort((a,b)=>Math.abs(st.x-a.x)-Math.abs(st.x-b.x))[0]||null;
 $('near').textContent=near?near.label+' · '+(near.kind==='golem'?'말 걸기':near.kind==='generator'?'렌치로 수리':near.kind==='ore'?'곡괭이로 캐기':'조사'):o.kind==='clear'?'메뉴에서 다음 챕터를 선택할 수 있어요.':'← → 이동 · ↑ ↓ 사다리';
 $('use').textContent=st.carried&&near?.kind!=='scale'?'내려놓기':near?.kind==='golem'?'말 걸기':near?.kind==='generator'?'수리':near?.kind==='ore'?'캐기':near?.kind==='weightCrate'?'들기':near?.kind==='scale'&&st.carried?'놓기':'조사';
 for(let i=0;i<5;i++){const b=$('hot'+i);b.classList.toggle('on',st.selectedHotbar===i&&C.owned(s,i));b.classList.toggle('dim',!C.owned(s,i));b.setAttribute('aria-pressed',st.selectedHotbar===i&&C.owned(s,i)?'true':'false');}
}
function step(dt){if(!running||mode||actionLock){if(actionLock){C.move(s,0,0,false,dt);refresh();}return;}const before=C.currentTask(s)?.id,h=(keys.has('right')||[...held.values()].includes('right')?1:0)-(keys.has('left')||[...held.values()].includes('left')?1:0),v=(keys.has('up')||[...held.values()].includes('up')?1:0)-(keys.has('down')||[...held.values()].includes('down')?1:0);C.move(s,h,v,jumpQueued,dt);jumpQueued=false;
 const st=current();if(before&&C.has(s,before)){save();effect(before,'목표를 해결했어요!');}if(st.plateEvent&&st.plateEvent.started!==lastPlateTime){lastPlateTime=st.plateEvent.started;if(!st.plateEvent.ok)notify('순서가 달라요. 다시 첫 숫자부터 시작해요.');}if(st.clock-lastSaved>4)save();refresh();}
function loop(ts){const dt=Math.min(.06,(ts-lastFrame)/1000||0);lastFrame=ts;if(!testMode){acc+=dt;for(let i=0;acc>=1/60&&i<5;i++){step(1/60);acc-=1/60;}}renderer.render(s,near,{mode,modal:!!mode,moving:held.size>0||keys.size>0,effect:worldEffect});requestAnimationFrame(loop);}
$('hotbar').innerHTML=D.tools.map((t,i)=>`<button class="slot dim" id="hot${i}" data-tool="${i}" aria-label="${t} 선택">${icon(i)}<span class="num">${i+1}</span></button>`).join('')+'<button class="slot" id="bagbtn" aria-label="가방">▣</button>';
D.tools.forEach((_,i)=>bind('hot'+i,()=>chooseTool(i)));bind('bagbtn',()=>{if(running)bag();});bind('mapbtn',()=>running?mapUI():title());bind('pausebtn',pause);bind('use',act);
$('jump').addEventListener('pointerdown',e=>{e.preventDefault();if(running&&!mode&&!actionLock)jumpQueued=true;});
document.querySelectorAll('[data-hold]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(!running||mode||actionLock)return;held.set(e.pointerId,b.dataset.hold);try{b.setPointerCapture(e.pointerId);}catch{}});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>held.delete(e.pointerId));});
const keyMap={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'};
window.addEventListener('keydown',e=>{if(mode){if(e.key==='Escape')close();else if(keyboard){e.preventDefault();keyboard(e);}return;}if(keyMap[e.key]){e.preventDefault();keys.add(keyMap[e.key]);}if(e.code==='Space'){e.preventDefault();if(!e.repeat)jumpQueued=true;}if(e.key.toLowerCase()==='e'&&!e.repeat)act();if(/^[1-5]$/.test(e.key))chooseTool(Number(e.key)-1);if(e.key.toLowerCase()==='i')bag();if(e.key==='Escape')pause();});window.addEventListener('keyup',e=>{if(keyMap[e.key])keys.delete(keyMap[e.key]);});window.addEventListener('blur',()=>{clearInput();save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();save();if(running)pause();}});window.addEventListener('pagehide',()=>{clearInput();save();});
window.MMApp={version:VERSION,get modal(){return mode;},inspect:()=>({campaign:JSON.parse(C.serialize(s)),state:JSON.parse(JSON.stringify(current())),objective:C.objective(s),waypoint:C.waypoint(s),boss:C.bossInfo(s),near:near?.id||null}),save};
// A deterministic clock for Playwright. It advances the exact normal input/physics loop, never teleports or changes flags.
if(testMode)window.MMApp.testFrames=n=>{if(!Number.isInteger(n)||n<0||n>2000)throw new Error('Invalid frame count');for(let i=0;i<n;i++)step(1/60);renderer.render(s,near,{mode,modal:!!mode,effect:worldEffect});};
title();refresh();requestAnimationFrame(loop);
})();
