/* Inserted inside the existing game closure by the checked release builder. */
function decorateBoss(id){if(mode!=='boss-question')return;const info=C.bossInfo(s),desc=C.descriptor(s,id),bar=document.createElement('div');bar.className='boss-quiz-strip';bar.id='bossQuizProgress';bar.innerHTML=`<strong>골렘 도전 ${info.done+1} / ${info.total}</strong><button class="btn small" id="pauseBoss">쉬기 · 저장</button>`;sheet.querySelector('.dialog-body').prepend(bar);bind('pauseBoss',close);sheet.dataset.quizId=id;const line=document.createElement('p');line.className='sub boss-question-line';line.textContent='골렘: '+desc.prompt;bar.after(line);}
function completeUI(id){save();sheet.dataset.feedback='success';const boss=mode==='boss-question',el=$('feedback');if(el){el.textContent=boss?'정답이에요! 잠시 후 다음 문제로 이어져요.':'정답이에요! 잘했어요.';el.classList.remove('bad');}sheet.querySelectorAll('.dialog-body button:not(#pauseBoss)').forEach(b=>b.disabled=true);
 later(()=>{if(boss&&!C.has(s,'clear')){const next=C.bossInfo(s).next;if(next){openPuzzle(next.id,true);return;}}close();effect(id,id.startsWith('boss.')?'골렘: 정답이야! 잘했어.':'장치가 작동했어요!');if(id.startsWith('boss.')&&C.has(s,'clear'))later(chapterClear,800);},1000);
}
function numberUI(id,titleText,boss){const p=C.puzzle(s,id),thinking=['cards','symbols'].includes(p.type);let answer='',locked=false;open(boss?'boss-question':'question',titleText,`${thinking?MMQuizView.markup(p)+'<p class="thinking-question" id="questionPrompt">'+esc(p.type==='symbols'?'찾은 수를 입력해요.':p.prompt)+'</p>':''}<div class="quizrow ${thinking?'thinking-answer':''}"><div>${!thinking&&boss?'<span class="tag" id="questionSpeaker">골렘이 낸 문제</span>':''}${!thinking?'<div class="equation" id="questionPrompt">'+esc(p.prompt)+'</div>':''}<div class="answer" id="answer" aria-live="polite">?</div><div class="feedback" id="feedback">숫자를 입력해 주세요.</div><button class="btn small" id="hint">모모의 힌트</button></div><div class="keys">${['1','2','3','4','5','6','7','8','9','⌫','0','확인'].map((v,i)=>`<button class="btn ${i===11?'primary':''}" id="key${i}">${v}</button>`).join('')}</div></div>`);if(thinking)MMQuizView.attach(p);save();sheet.dataset.quizId=id;
 const render=()=>{$('answer').textContent=answer||'?';};function submit(){if(locked||!answer)return;const r=C.submit(s,id,answer);if(r.solved){locked=true;completeUI(id);}else{$('feedback').textContent='괜찮아요. 단서를 하나씩 다시 살펴봐요.';$('feedback').classList.add('bad');answer='';render();save();}}
 for(let i=0;i<12;i++)bind('key'+i,()=>{if(locked)return;if(i<9&&answer.length<3)answer+=i+1;else if(i===9)answer=answer.slice(0,-1);else if(i===10&&answer.length<3)answer+='0';else if(i===11)submit();render();});let hints=0;bind('hint',()=>{hints++;if(p.type==='symbols'){$('feedback').textContent=hints===1?p.hint:hints===2?`별부터 알아봐요. ★ = ${p.explanation?.[0]??'?'}`:'함께 확인해요: '+p.answer;}else if(p.type==='cards'){$('feedback').textContent=hints===1?p.hint:hints===2?'활동 한 단계 보기를 누르고, 처음 줄과 달라진 자리를 비교해요.':'함께 확인해요: '+p.answer;}else $('feedback').textContent=hints>1?'함께 확인해요: '+p.answer:p.hint;});keyboard=e=>{if(locked)return;if(/^\d$/.test(e.key)&&answer.length<3){answer+=e.key;render();}else if(e.key==='Backspace'){answer=answer.slice(0,-1);render();}else if(e.key==='Enter')submit();};
}
