const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function load(){const file=path.resolve(__dirname,'../../..','_site/index.html');a.ok(fs.existsSync(file),'15.2 build exists');const html=fs.readFileSync(file,'utf8'),ctx={console};ctx.globalThis=ctx;vm.createContext(ctx);for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)){if(m[1].includes('Mobile UI for'))break;vm.runInContext(m[1],ctx);}return ctx;}
const j=x=>JSON.parse(JSON.stringify(x));
test('shipped source contains 15.2 counts and one field thinking device per chapter',()=>{const {MM:C,MMChapters:D,MMQuiz:Q}=load();for(const d of D.list()){a.equal(d.boss.questions.length,Q.profile(d.order).bossCount);a.equal(d.tasks.filter(t=>t.id==='thinking.beacon').length,1);a.ok([...d.tasks,...d.boss.questions].some(q=>q.type==='cards'));a.ok(d.boss.questions.some(q=>q.type==='symbols'));a.ok(d.tasks.every(t=>t.x>0&&t.x<d.width));}});
test('campaign avoids identical recent numeric/logic questions and persists chosen variants',()=>{const {MM:C,MMChapters:D,MMQuiz:Q}=load();let s=C.fresh(414),keys=[];for(const d of D.list()){s.unlockedChapters.push(d.id);C.startChapter(s,d.id);for(const q of [...d.tasks,...d.boss.questions,...d.encounters].filter(q=>['number','cards','symbols','rule','monster'].includes(q.type))){const p=C.puzzle(s,q.id),key=Q.fingerprint(p);a.ok(!keys.slice(-128).includes(key),d.id+' repeated '+key);keys.push(key);const saved=C.restore(C.serialize(s));a.ok(saved);a.equal(Q.fingerprint(C.puzzle(saved,q.id)),key);a.equal(C.puzzle(saved,q.id).answer,p.answer);s=saved;}s.completedChapters.push(d.id);}a.ok(keys.length>80);a.ok(s.quizBook.recent.length<=128);});
test('unfinished cards and symbols survive reload, wrong input cannot give rewards twice',()=>{const {MM:C,MMChapters:D}=load();let s=C.fresh(51),st=C.session(s),d=D.get(s.chapter);st.flags=d.tasks.map(t=>t.id);s.inventory.owned.fill(true);s.inventory.equipped.fill(true);for(const q of d.boss.questions){const p=C.puzzle(s,q.id);if(['cards','symbols'].includes(p.type)){const before=C.serialize(s),xp=s.xp,inv=j(s.inventory);a.equal(C.submit(s,q.id,String(p.answer+1)).ok,false);a.equal(s.xp,xp);a.deepEqual(j(s.inventory),inv);s=C.restore(C.serialize(s));a.ok(s);const restored=C.puzzle(s,q.id);a.equal(restored.answer,p.answer);a.ok(C.submit(s,q.id,String(p.answer)).ok);const after=s.xp;a.equal(C.submit(s,q.id,String(p.answer)).ok,false);a.equal(s.xp,after);}else C.session(s).flags.push(q.id);}});
test('completed 15.1 chapters remain completed when additional tasks are installed',()=>{const {MM:C}=load();let s=C.fresh(80);s.completedChapters=['chapter-01','chapter-02'];C.session(s).flags=['clear'];const r=C.restore(C.serialize(s));a.ok(r);a.equal(C.bossInfo(r).cleared,true);a.ok(C.startChapter(r,'chapter-02'));a.equal(C.currentTask(r),null);a.ok(r.unlockedChapters.includes('chapter-03'));});
test('build has no copied workbook photos, and UI has explicit continuous boss controls',()=>{const {MMQuiz:Q}=load();a.ok(Q);const html=fs.readFileSync(path.resolve(__dirname,'../../..','_site/index.html'),'utf8');a.ok(html.includes('pauseBoss'));a.ok(html.includes('decorateBoss'));a.ok(html.includes('cardsWorkbench'));a.ok(!html.includes('file_00000000'));});

test('every boss puzzle dispatcher, not only machines, decorates progress and pause',()=>{load();const html=fs.readFileSync(path.resolve(__dirname,'../../..','_site/index.html'),'utf8'),start=html.indexOf('function openPuzzle('),end=html.indexOf('function mechanismUI(',start);a.ok(html.slice(start,end).includes('if(boss)decorateBoss(id)'));});
test('pipe entry and exit labels track randomized endpoint rows',()=>{load();const html=fs.readFileSync(path.resolve(__dirname,'../../..','_site/index.html'),'utf8');a.ok(html.includes('grid-row:${p.source[1]+1}'));a.ok(html.includes('grid-row:${p.target[1]+1}'));});
