const test=require('node:test'),a=require('node:assert/strict');
let Q;try{Q=require('./rules.js');}catch{}
test('card actions use the current position, not the card number',()=>{a.ok(Q,'quiz rules exist');const states=Q.cardStates([1,2,3,4,5,6,7,8,9],[{kind:'front',from:4},{kind:'end',from:3},{kind:'swap',from:5,to:6}]);a.deepEqual(states.at(-1),[4,1,3,5,7,6,8,9,2]);a.equal(Q.cardAnswer(states[0],states.at(-1),'difference'),3);});
test('symbol clues have exactly one integer solution and give the advertised answer',()=>{a.ok(Q);for(let level=1;level<=15;level++)for(let seed=1;seed<=60;seed++){const p=Q.symbols(seed,level);const solutions=[];for(let x=0;x<=20;x++)for(let y=0;y<=20;y++)for(let z=0;z<=(p.variables===3?20:0);z++){const v=[x,y,z];if(p.clues.every(c=>c.left.reduce((n,t)=>n+(typeof t==='string'?v[Number(t)]:t),0)===(typeof c.right==='string'?v[Number(c.right)]:c.right)))solutions.push(v);}a.equal(solutions.length,1,JSON.stringify(p));a.equal(solutions[0][p.ask],p.answer);}});
test('generated card solutions are valid, reproducible and nontrivial',()=>{a.ok(Q);for(let chapter=1;chapter<=15;chapter++)for(let seed=1;seed<=120;seed++){let p=Q.cards(seed,chapter);a.deepEqual(p,Q.cards(seed,chapter));a.equal(Q.cardAnswer(p.cards,Q.cardStates(p.cards,p.operations).at(-1),p.ask,p.position),p.answer);a.ok(Number.isInteger(p.answer)&&p.answer>=0&&p.answer<100);a.ok(p.operations.length<4);a.notDeepEqual(p.cards,Q.cardStates(p.cards,p.operations).at(-1));if(p.ask==='difference')a.ok(p.unchanged.length>=2);}});
test('quiz budgets increase by small bands and preserve easy multiplication',()=>{a.ok(Q);a.deepEqual([1,3,4,6,7,9,10,12,13,15].map(n=>Q.profile(n).bossCount),[5,5,6,6,7,7,8,8,9,9]);for(let n=1;n<=15;n++){let p=Q.profile(n);a.deepEqual(p.tables,[2,3,5]);a.ok(p.memory<=5);}});
test('newly generated rules, pipe and laser boards have meaningful variety',()=>{const vm=require('node:vm'),{scripts}=require('./build.cjs').build(),ctx={};ctx.globalThis=ctx;vm.createContext(ctx);for(const code of scripts){if(code.includes('Mobile UI for'))break;vm.runInContext(code,ctx);}const P=ctx.MMPuzzles;for(const type of ['rule','pipe','laser']){const seen=new Set();for(let i=1;i<=100;i++){const p=P.create(type,i,{chapterOrder:8,level:5});seen.add(Q.fingerprint(p));if(type==='pipe')a.ok(P.solvePipe(p));if(type==='laser')a.ok(P.solveLaser(p));}a.ok(seen.size>=12,type+' has '+seen.size+' layouts');}});

test('all graded arithmetic answers are correct, integral, non-negative and below 100',()=>{for(let chapter=1;chapter<=15;chapter++)for(let seed=1;seed<=150;seed++)for(const mode of ['add','sub','mul','div','missing','pattern','twoStep','divideAdd']){const p=Q.arithmetic(seed,mode,chapter);const answer=({add:()=>p.a+p.b,sub:()=>p.a-p.b,mul:()=>p.a*p.b,div:()=>p.a/p.b,missing:()=>p.b-p.a,pattern:()=>p.a+3*p.b,twoStep:()=>p.a+p.b-p.c,divideAdd:()=>p.a/p.b+p.c})[mode]();a.equal(p.answer,answer);a.ok(Number.isInteger(p.answer)&&p.answer>=0&&p.answer<100);if(mode==='mul')a.ok([2,3,5].includes(p.a));if(mode==='div'||mode==='divideAdd'){a.ok([2,3,5].includes(p.b));a.equal(p.a%p.b,0);}}});
