/* Original interactive visual aids. They do not modify the answer or award progress. */
(function(root){'use strict';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shapes=['★','▲','■'],names=['별','세모','네모'];
function token(x){return typeof x==='string'?`<span class="shape shape-${x}" aria-label="${names[+x]}">${shapes[+x]}</span>`:`<span class="known-number">${x}</span>`;}
function actionText(o){return o.kind==='swap'?`현재 줄의 왼쪽 ${o.from}번째와 ${o.to}번째 카드를 서로 바꿔요.`:`현재 줄의 왼쪽 ${o.from}번째 카드를 ${o.kind==='front'?'맨 앞으로':'맨 뒤로'} 옮겨요.`;}
function row(xs,interactive=false){return xs.map((v,i)=>`<${interactive?'button':'span'} class="number-card" ${interactive?`type="button" data-card="${i}" aria-label="왼쪽 ${i+1}번째 카드 ${v}"`:''}><small>${i+1}번째</small><b>${v}</b></${interactive?'button':'span'}>`).join('');}
function markup(p){if(p.type==='symbols')return `<section class="thinking-panel" aria-label="같은 모양의 값 찾기"><p class="help">같은 모양에는 언제나 같은 수가 들어가요.</p><div class="symbol-clues">${p.clues.map((c,i)=>`<div class="symbol-clue"><small>단서 ${i+1}</small><div class="symbol-equation">${c.left.map(token).join('<span>+</span>')}<span>=</span>${token(c.right)}</div></div>`).join('')}</div><div class="symbol-ask">${token(String(p.ask))}<span>는 얼마일까요?</span></div></section>`;
 if(p.type==='cards')return `<section class="thinking-panel" aria-label="카드 위치 바꾸기"><p class="sub">처음 줄 · 작은 수부터 놓았어요.</p><div class="card-row" style="--count:${p.cards.length}">${row(p.cards)}</div><ol class="card-activities">${p.operations.map(o=>`<li>${esc(actionText(o))}</li>`).join('')}</ol><p class="sub">직접 움직여 봐요 · 두 카드를 차례로 누르면 서로 바뀌어요.</p><div id="cardsWorkbench" class="card-row" style="--count:${p.cards.length}">${row(p.cards,true)}</div><div class="card-controls"><button class="btn small" id="cardFront">맨 앞으로</button><button class="btn small" id="cardEnd">맨 뒤로</button><button class="btn small" id="cardReset">처음 줄</button></div><div class="card-controls"><button class="btn" id="cardStep">활동 한 단계 보기</button><span id="cardStepInfo" role="status">0 / ${p.operations.length}</span></div><p class="sub">카드를 움직여도 정답이 자동으로 입력되지는 않아요.</p></section>`;
 return '';}
function attach(p,doc=document){if(p.type!=='cards')return;let board=p.cards.slice(),picked=-1,step=0;const states=root.MMQuiz.cardStates(p.cards,p.operations),box=doc.getElementById('cardsWorkbench');
 function paint(animate=true){const old=Array.from(box.children).map(e=>({v:+e.querySelector('b').textContent,r:e.getBoundingClientRect()}));box.innerHTML=row(board,true);Array.from(box.children).forEach((el,i)=>{el.classList.toggle('chosen',picked===i);el.onclick=()=>{if(picked<0){picked=i;}else if(picked===i)picked=-1;else{[board[picked],board[i]]=[board[i],board[picked]];picked=-1;}paint();};const before=old.find(x=>x.v===board[i]),after=el.getBoundingClientRect();if(animate&&before&&el.animate&&!doc.defaultView.matchMedia('(prefers-reduced-motion: reduce)').matches)el.animate([{transform:`translate(${before.r.x-after.x}px,${before.r.y-after.y}px)`},{transform:'translate(0,0)'}],{duration:420,easing:'ease-out'});});doc.getElementById('cardFront').disabled=picked<0;doc.getElementById('cardEnd').disabled=picked<0;}
 const bind=(id,fn)=>doc.getElementById(id).onclick=fn;bind('cardFront',()=>{board.unshift(board.splice(picked,1)[0]);picked=-1;paint();});bind('cardEnd',()=>{board.push(board.splice(picked,1)[0]);picked=-1;paint();});bind('cardReset',()=>{board=p.cards.slice();picked=-1;step=0;doc.getElementById('cardStepInfo').textContent=`0 / ${p.operations.length}`;doc.getElementById('cardStep').disabled=false;paint();});bind('cardStep',()=>{step=Math.min(step+1,p.operations.length);board=states[step].slice();picked=-1;doc.getElementById('cardStepInfo').textContent=`${step} / ${p.operations.length}`;doc.getElementById('cardStep').disabled=step===p.operations.length;paint();});paint(false);
}
root.MMQuizView={markup,attach,actionText,token};
})(globalThis);
